### ISSUE TITLE
CloudFormation files

### ISSUE THREAD

**Issue by JohnTigue** [aws/aws-gamekit-unity#1]
Are there CloudFormations template files that adopters can extend? 

For example, I would like take the work that has been done to federated Facebook identities and extend it to also federated Google identities.

**Comment by amzn-imdasor** [comment]
Hi John,

I hope  [this](https://repost.aws/questions/QU0_pLVyv4TySgM35wC2_ptQ/is-it-possible-to-use-game-kit-identity-and-authentication-with-steam-epic-accounts-xbox-and) answers your question.

Please let me know if you need additional details.

**Comment by JohnTigue** [comment]
Thanks. Indeed that does provide detailed instructions on adding a new federated ID source. And it has the link to the CloudFormations template YAML: https://github.com/aws/aws-gamekit-unity/tree/main/Packages/com.amazonaws.gamekit/Editor/CloudResources/.BaseTemplates/cloudformation/identity
